Add DomainRegistrantChange event types
dnsimple/dnsimple-go pull request #148
Opened 2023-09-01 05:08 UTC by wilson-dnsimple

Add the struct type for the `domain.registrant_change` events.

https://github.com/dnsimple/dnsimple-business/issues/1729

2023-09-01 06:03 UTC, DXTimer requested changes

2023-09-01 06:03 UTC, DXTimer commented on dnsimple/webhook/events.go
The event types also need to be added to the event types switch statement: https://github.com/dnsimple/dnsimple-go/pull/149/files#diff-22dab29957af6fba80649e7bc447dd4587d4d23963b73db5e7c2fc6803868025R10

2023-09-01 06:13 UTC, wilson-dnsimple commented on dnsimple/webhook/events.go
I think it already exists: https://github.com/dnsimple/dnsimple-go/blob/76d7b2cea116a1680ec2f95838aeb60249c0d330/dnsimple/webhook/events.go#L44

2023-09-01 06:15 UTC, DXTimer commented on dnsimple/webhook/events.go
`domain.registrant_change:started` and `domain.registrant_change:cancelled` are missing.

2023-09-05 12:11 UTC, DXTimer requested changes
Can you also add tests for the new events in `events_test.go`?

2023-09-07 09:59 UTC, DXTimer approved these changes

2023-09-11 11:29 UTC, merged